#!/bin/bash
#    bl-compositor: un Pipe Menu Openbox pour compton compositor
#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
#    Copyright (C) 2013 Aleks-Daniel Jakimenko
#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
#    Traduis par Luvalem
#
#    Ce programme est un logiciel libre: vous pouvez le redistribuer
#    et / ou le modifier selon les termes de la Licence Publique 
#    Générale GNU publiée par la Free Software Foundation,
#    soit la version 3 de la licence, soit (à votre choix)
#    toute version ultérieure.
#
#    Ce programme est distribué dans l'espoir qu'il sera utile,
#    Mais SANS AUCUNE GARANTIE; Sans même la garantie implicite de
#    QUALITÉ MARCHANDE OU ADAPTATION À UN USAGE PARTICULIER.  Voir la
#    GNU General Public License pour plus de détails.
#
#   Vous devriez avoir reçu une copie de la Licence Publique 
#   Générale GNUavec ce programme.  Sinon, voir 
#   <http://www.gnu.org/licenses/>.

HELP='    bl-compositor est un Pipe Menu Openbox pour utiliser compton compositor
    il est normalement appelé par openbox menu.

Options (usually passed from the menu):
    -h --help   Affiche ce message
    --start     démarre compositor and relance tint2, si Actif
    --restart   relance compositor, si Actif, et relance tint2
    --stop      stop compositor
    --edit      ouvre le fichier de configuration compton dans un éditeur de texte
    --watch     redémarre compositor chaque fois que le fichier de configuration est modifié
    (--Watch est utile pour le débogage)

    Si bl-compositor est appelé sans options (la methode habituelle),
    il sortira un fichier openbox pipemenu xml pour modifier l`effet composite.

voir ~/.config/compton.conf et "man compton" pour les options de configuration.
'
# Cherchez une option d'aide quelque part
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

RESTART_ATTEMPTS=20 # Le temps d'essayer killall avant de revenir à -s KILL

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Echec de la source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

declareDependencies compton

# ------------- Set compton command options -----------------------------------
EXECXCOMP='compton -b'
if glxinfo | egrep -iq 'rendu direct: oui'; then
    EXECXCOMP+=' --vsync opengl'
fi

forcekill_compton() {
    killall -q compton
    for (( i=0; i < RESTART_ATTEMPTS; i++ )); do
        pidof compton > /dev/null ||
            break

        (( i == RESTART_ATTEMPTS - 1 )) &&
            killall -q -S KILL compton

        sleep 0.25
    done
}


if [[ $1 = '--edit' ]]; then # Editer la configuration compton
    [[ ! -f $HOME/.config/compton.conf ]] &&
        cp '/etc/xdg/compton.conf' "$HOME/.config/compton.conf"

    if type bl-text-editor >/dev/null;then
        bl-text-editor "$HOME/.config/compton.conf"
    else
        x-terminal-emulator -T 'edit compton.conf' -e nano "$HOME/.config/compton.conf"
    fi
elif [[ $1 = '--start' ]]; then
    if ! pidof compton > /dev/null; then
        $EXECXCOMP
        bl-tint2restart || true
    else
        echo "$0 --start: compton est actif" >&2
    fi
elif [[ $1 = '--stop' ]]; then
    forcekill_compton
elif [[ $1 = '--restart' ]]; then
    if pidof compton > /dev/null; then
        forcekill_compton
        "$0" --start
    else # nothing to restart
        echo "$0 --restart: compton n est pas actif" >&2
    fi
elif [[ $1 = '--watch' ]]; then
    while inotifywait -e close_write "$HOME/.config/compton.conf"; do
        "$0" --restart
    done
else
    # Output Openbox menu
    menuStart
    if ! pidof compton > /dev/null; then
        menuItem 'Activer Composite' "$0 --start"
    else
        menuItem 'Redémmarer Composite' "$0 --restart"
        menuItem 'Désactiver Composite' "$0 --stop"
        menuSeparator
    fi
    menuItem 'Editer config Composite' "$0 --edit"
    menuEnd
fi
exit 0
