#!/bin/bash

#    bl-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
#    Copyright (C) 2015-2016 damo    <damo@bunsenlabs.org>
#    Traduis par Luvalem
#
#    Ce programme est un logiciel libre: vous pouvez le redistribuer
#    et / ou le modifier selon les termes de la Licence Publique 
#    Générale GNU publiée par la Free Software Foundation,
#    soit la version 3 de la licence, soit (à votre choix)
#    toute version ultérieure.
#
#    Ce programme est distribué dans l'espoir qu'il sera utile,
#    Mais SANS AUCUNE GARANTIE; Sans même la garantie implicite de
#    QUALITÉ MARCHANDE OU ADAPTATION À UN USAGE PARTICULIER.  Voir la
#    GNU General Public License pour plus de détails.
#
#   Vous devriez avoir reçu une copie de la Licence Publique 
#   Générale GNUavec ce programme.  Sinon, voir 
#   <http://www.gnu.org/licenses/>.

HELP='    bl-tint2-pipemenu un pipemenu Openbox pour modifier tint2
    Il est normalement appele par Openbox Menu.

Options:
    -h --help   affiche ce message

    If bl-tint2-pipemenu est appele sans option (la methode usuelle),
    Il sortira un pipemenu xml openbox pour la gestion des sessions
     tint2 et l édition des fichiers de configuration.

Pour plus d informations, voir "man tint2"
et "Help">"Tint2" in the BunsenLabs menu.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'

TINT2PATH="$HOME/.config/tint2"
TINT2RC="$TINT2PATH/tint2rc"
TZEN="bl-tint2zen"

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Échec de la source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

loadTEditmenu(){
    menuSeparator
    menuItem "Editer tint2rc" "bl-text-editor $TINT2RC"
    if [ "$(pidof tint2)" ];then
        menuSubmenu "RunningTint2" "Tint2s Actuel"
        pgrep -a tint2 | while read -r pid cmd; do
            if [[ ${cmd%% *} = tint2 ]]; then
                TINT=${cmd##* }
                TINT2=${TINT#$HOME/.config/}
                if [[ $TINT = tint2 ]];then
                    TINT="$TINT2RC"
                    TINT2="Default tint2rc"
                fi
                menuItem "$TINT2" "bl-text-editor $TINT"
            fi
        done
        menuSubmenuEnd
    fi
}

getTint2s(){
    menuSubmenu "EditTint2" "Editer Tint2s"
        if type bl-tint2edit &>/dev/null;then  # bl-tint2edit script found
            menuItem "Editeur Tint2" "bl-tint2edit"
            loadTEditmenu
        else
            loadTEditmenu
        fi
    menuSubmenuEnd
}

loadChoosermenu(){
    if type $TZEN &>/dev/null;then  # bl-tint2zen script found
        menuItem "Choisir Tint2" "$TZEN"
    fi
}

loadRestartmenu(){
    if [ "$(pidof tint2)" ];then
        if type bl-tint2restart &>/dev/null;then  # bl-tint2restart script found
            menuItem "Relancer Tint2" "bl-tint2restart"
        fi
    fi
}

menuStart "Tintmenu" "Tint2"
loadChoosermenu
loadRestartmenu
getTint2s
menuEnd
