#!/bin/bash
#
#    bl-tintedit: a BunsenLabs un éditeur de fichier config tint2
#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
#
#    Copyright (C) 2010~2016  John Crawley <john@bunsenlabs.org>
#    Traduis par Luvalem
#
#    Ce programme est un logiciel libre: vous pouvez le redistribuer
#    et / ou le modifier selon les termes de la Licence Publique 
#    Générale GNU publiée par la Free Software Foundation,
#    soit la version 3 de la licence, soit (à votre choix)
#    toute version ultérieure.
#
#    Ce programme est distribué dans l'espoir qu'il sera utile,
#    Mais SANS AUCUNE GARANTIE; Sans même la garantie implicite de
#    QUALITÉ MARCHANDE OU ADAPTATION À UN USAGE PARTICULIER.  Voir la
#    GNU General Public License pour plus de détails.
#
#   Vous devriez avoir reçu une copie de la Licence Publique 
#   Générale GNUavec ce programme.  Sinon, voir 
#   <http://www.gnu.org/licenses/>.
#
########################################################################
#
#   les fichiers Tint2 doivent être dans $TINT2PATH
#
#   Les tint2s cochés sont ouverts dans l'éditeur de texte.
#   Plusieurs Tint2 peuvent être choisis
#
########################################################################

TINT2PATH="$HOME/.config/tint2"

HELP="Bl-tint2edit un script pour modifier les fichiers de configuration
tint2 sélectionnés

Options:
    -h --help   affiche cemessage

Pas d'autres options disponibles.

Les fichiers Tint2 doivent être edans $TINT2PATH
Les tint2s cochés sont ouverts dans l'éditeur de texte.
Plusieurs Tint2 peuvent être choisis
"

### DIALOG VARIABLES
DLGDEC="yad --center  --borders=20 --width=400 --height=400 "
TITLE="BunsenLabs Tint2 Edit"
WINICON="--window-icon=distributor-logo-bunsenlabs"
OK="--button=OK:0"
CANCEL="--button=gtk-cancel:1"

########## FUNCTIONS ###################################################

fillArrays(){
    num="$1"
    tintsPath[$num]="$2"   # Chemin d'accès complet à tint2
    tintsArr[$num]="$3"    # Nom affiché: "répertoire / fichier tint"
}

findTint(){
# recherche de dossiers pour les fichier de configuration tint2
    num=0
    for x in $(find $TINT2PATH -type f );do
        # check if likely tint2 config file
        pm=$(grep  "panel_monitor" "$x")
        if [[ $pm ]];then
            TINT2=$( echo $x | awk -F"/" '{print $(NF-1)"/"$NF}')
            fillArrays $num $x $TINT2
            num=$(($num+1))
        fi
    done
}
######## END FUNCTIONS #################################################

# Cherche une option d'aide quelque part
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

# Obtenir les répertoires tint2, ajouter au tableau
findTint

# Boucler les tableaux et créer un texte msg pour la boîte de dialogue yad
unset LISTINT
for ((j=0; j<${#tintsArr[*]}; j++));do
    LISTINT="$LISTINT FALSE ${tintsArr[j]} "
done
## Populate dialog from array, get return value(s)
RET=$($DLGDEC $WINICON --list --title="$TITLE" \
    --text="Sélectionnez Tint2s pour editerer dans la liste\nPlusieurs Tint2s peuvent être choisis\n" \
    --checklist \
    --column="Select:CHK" --column="Tint2 Name:TXT" $LISTINT --separator=":" \
    $OK $CANCEL \
    )

if (( $? == 1 )); then # Bouton d'annulation enfoncé
    exit 0
else
    i=0
    OIFS=$IFS   # Enregistrer Internal Field Separator
    IFS=":"     # Séparateur est ":" dans les choix retournés
    for name in $RET; do
        retTint[$i]="$name"
        i=$(($i+1))
    done
    IFS=$OIFS   # Réinitialiser IFS à la valeur par défaut

    # Trouver les tint2s choisies et les modifier
    for name in ${retTint[*]};do       # Boucle à travers les noms tint2 cochés
        for ((j=0; j<${#tintsPath[*]}; j++));do  # traverse Par des éléments
            for f in ${tintsPath[j]};do    # Comparer avec le choix de la boîte de dialogue
                display=$( echo "$f" | awk -F"/" '{print $(NF-1)"/"$NF}')
                if [[ $display = $name ]];then
                    bl-text-editor "$f"
                fi
            done
        done
    done
fi

exit 0
