#!/bin/bash
#
#    bl-tint2restart: un script pour redemarrer toutes les instances tint2
#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
#    Copyright (C) 2015-2016  John Crawley <john@bunsenlabs.org>
#    Traduis par Luvalem
#
#     Ce programme est un logiciel libre: vous pouvez le redistribuer
#    et / ou le modifier selon les termes de la Licence Publique 
#    Générale GNU publiée par la Free Software Foundation,
#    soit la version 3 de la licence, soit (à votre choix)
#    toute version ultérieure.
#
#    Ce programme est distribué dans l'espoir qu'il sera utile,
#    Mais SANS AUCUNE GARANTIE; Sans même la garantie implicite de
#    QUALITÉ MARCHANDE OU ADAPTATION À UN USAGE PARTICULIER.  Voir la
#    GNU General Public License pour plus de détails.
#
#   Vous devriez avoir reçu une copie de la Licence Publique 
#   Générale GNUavec ce programme.  Sinon, voir 
#   <http://www.gnu.org/licenses/>.

HELP='    bl-tint2-restart est un script pour redemarrer les instances de Tint2 Actives

Options:
    -h --help   Affiche ce message

Pas d autres options supportees.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

pidof tint2 >/dev/null || {
    echo "$0: pas de processus tint2 trouves" >&2
    exit 1
}

declare -A commands # Tableau associatif

while read pid cmd; do
    if [[ ${cmd%% *} = tint2 ]]; then
        kill "$pid"
        commands[$cmd]=1 # Les commandes en double ne seront lancées qu'une seule fois
    fi
done <<< "$(pgrep -a tint2)"

sleep 1

# Tous les processus en cours d'exécution seront tués avec SIGKILL
while read pid cmd; do
    if [[ ${cmd%% *} = tint2 ]]; then
        kill -KILL "$pid"
        commands[$cmd]=1
    fi
done <<< "$(pgrep -a tint2)"

sleep 1
for i in "${!commands[@]}" # Passer en revue les index
do
    (setsid $i &)
    sleep 0.1
done

#sleep 1
#bl-compositor --restart  # restart compositor

exit 0
